# -*- coding: utf-8 -*-
"""Suvikhyath_2503B05202_ADSA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14g_-15pxoO8Q9QZZoHQY2oVBxGebWEdV
"""

class PassengerNode:
    def __init__(self, name):
        self.name = name
        self.next = None


class FlightNode:
    def __init__(self, flight_no):
        self.flight_no = flight_no
        self.passengers = None
        self.next = None


class AirlineSystem:
    def __init__(self):
        self.flight_head = None

    def add_flight(self, flight_no):
        new_fight = FlightNode(flight_no)

        if self.flight_head is None or flight_no < self.flight_head.flight_no:
            new_fight.next = self.flight_head
            self.flight_head = new_fight
            print(f"Flight {flight_no} added.")
            return

        current = self.flight_head
        while current.next and current.next.flight_no < flight_no:
            current = current.next

        new_fight.next = current.next
        current.next = new_fight
        print(f"Flight {flight_no} added.")

    def get_flight(self, flight_no):
        current = self.flight_head
        while current:
            if current.flight_no == flight_no:
                return current
            current = current.next
        return None

    def reserve(self, flight_no, name):
        flight = self.get_flight(flight_no)
        if not flight:
            print("Flight not found!")
            return

        new_passenger = PassengerNode(name)

        if flight.passengers is None or name < flight.passengers.name:
            new_passenger.next = flight.passengers
            flight.passengers = new_passenger
            print(f"{name} reserved on {flight_no}")
            return

        current = flight.passengers
        while current.next and current.next.name < name:
            current = current.next

        new_passenger.next = current.next
        current.next = new_passenger
        print(f"{name} reserved on {flight_no}")

    def cancel(self, flight_no, name):
        flight = self.get_flight(flight_no)
        if not flight:
            print("Flight not found!")
            return

        head = flight.passengers
        if head is None:
            print("No reservations on this flight.")
            return

        if head.name == name:
            flight.passengers = head.next
            print(f"{name} cancelled from {flight_no}")
            return

        current = head
        while current.next and current.next.name != name:
            current = current.next

        if current.next is None:
            print("Passenger not found.")
        else:
            current.next = current.next.next
            print(f"{name} cancelled from {flight_no}")

    def display(self):
        if self.flight_head is None:
            print("No flights available.")
            return

        current = self.flight_head
        while current:
            print(f"\nFlight: {current.flight_no}")
            p = current.passengers

            if p is None:
                print("  No passengers.")
            else:
                print("  Passengers:")
                while p:
                    print("   -", p.name)
                    p = p.next

            current = current.next


# ---------------------- MENU DRIVEN PROGRAM ----------------------

def main():
    system = AirlineSystem()

    while True:
        print("\n--- Airline Reservation System ---")
        print("1. Add Flight")
        print("2. Reserve Ticket")
        print("3. Cancel Ticket")
        print("4. Display Flights & Passengers")
        print("5. Exit")

        choice = input("Enter your choice: ")

        if choice == "1":
            flight_no = input("Enter flight number: ")
            system.add_flight(flight_no)

        elif choice == "2":
            flight_no = input("Enter flight number: ")
            name = input("Enter passenger name: ")
            system.reserve(flight_no, name)

        elif choice == "3":
            flight_no = input("Enter flight number: ")
            name = input("Enter passenger name to cancel: ")
            system.cancel(flight_no, name)

        elif choice == "4":
            system.display()

        elif choice == "5":
            print("Exiting the system...")
            break

        else:
            print("Invalid choice! Please try again.")


# Start program
main()

